name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload Fabric Mod
      uses: actions/upload-artifact@v4
      with:
        name: Sakura-Fabric
        path: fabric/build/libs/

    - name: Upload NeoForge Mod
      uses: actions/upload-artifact@v4
      with:
        name: Sakura-NeoForge
        path: neoforge/build/libs/
